name: image_cropper_for_web
description: A new Flutter package project.
repository: https://github.com/hnvn/flutter_image_cropper
version: 0.0.1

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  
  image_cropper_platform_interface: ^2.0.0-beta.1

  js: ^0.6.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

