name: image_cropper
description: A Flutter plugin supports cropping images
version: 0.0.2
author: hunghd <hunghd.yb@gmail.com>
homepage: https://github.com/hnvn/flutter_image_cropper

environment:
  sdk: '>=1.19.0 <2.0.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: vn.hunghd.flutter.plugins.imagecropper
    iosPrefix: FLT
    pluginClass: ImageCropperPlugin